### ISSUE TITLE
nginx 1.9.5 (or higher) ?

### ISSUE THREAD

**Issue by jult** [Entware-ng/Entware-ng#285]
the "http2" parameter requires ngx_http_v2_module in /opt/etc/nginx/conf.d/x.conf

I bumped into this when I copied over a config from a Pi3 server elsewhere.
Would be great to have http2 support in entware-ng.

**Comment by ryzhovau** [comment]
Done, nginx version bumped to 1.10.0. Binaries will arrive soon.

**Comment by jult** [comment]
Eeh.. where did you get the 1.10 from? http://nginx.org/en/CHANGES
I still get the same error with this release;

    [emerg] the "http2" parameter requires ngx_http_v2_module in /etc/nginx/conf.d/ conf:

**Comment by ryzhovau** [comment]
> Eeh.. where did you get the 1.10 from?

So, why don't you read nginx.org?

**Comment by jult** [comment]
Never mind, all this entware stuff ends up being a huge waste of (my) time. I fired up OpenMediaVault distro on a raspberry pi, removed all the seafile complexity and went back to syncthing, because, well, OVM offers user separated instances, managed by webbased UI. I can recommend that highly. I litterally had it setup and running stable in an hour, replacing all my seafile/seahub/seadav users and all other entware-ng packages I used before. http://forums.openmediavault.org/index.php/Thread/8759-Syncthing/?pageNo=6
