### ISSUE TITLE
Package request: SoftEther

### ISSUE THREAD

**Issue by relictMarauder** [Entware-ng/Entware-ng#319]
Hi,

Is it possible to include softether? https://www.softether.org/

**Comment by ryzhovau** [comment]
Too heavy even for PC, [too low performance](http://www.linksysinfo.org/index.php?threads/ultime-vpn-server-sstp-ipsec-need-help-compiling-it.68611/) with it's userspace NAT.

You can do your own tests with binaries, provided by [tomatoware](https://github.com/lancethepants/tomatoware).

**Comment by relictMarauder** [comment]
I use the softether about two years. Ich no problem with performance. The userspace NAT performance problem is fixed in october 2015. Many people use Softether in OpenWrt devices oder Fritzboxes without performance problems. example: https://github.com/el1n/OpenWRT-package-softether
http://wordpress.tirlins.com/2015/03/setting-up-softether-vpn-on-openwrt/
etc.

**Comment by ryzhovau** [comment]
Unfortunately, it's [still not cross-compilation friendly](https://github.com/Entware-ng/graveyard/commit/2b5823d22e83a24dfef70c85f6eb19080a2b83d8) so I recommend to use @lancethepants's static build.

I'll keep this issue open, keeping eye on SoftEtherVPN development.

**Comment by zyxmon** [comment]
@relictMarauder - what is your feed/architecture.

**Comment by zyxmon** [comment]
No response. Package added without user testing https://github.com/Entware-ng/entware-packages/commit/78c19852f1346c7fb2c283eed150daa9c5422f0f

**Comment by ryzhovau** [comment]
PS For ARM/x86 only.

**Comment by slashmax** [comment]
Can be added for armv7? I can test on asus ac87u. Thx.

**Comment by zyxmon** [comment]
@slashmax binary package will be in repo soon.

**Comment by slashmax** [comment]
@zyxmon thx, installed and works great so far. Geting 100Mbps download and 66Mbps upload over vpn.
